// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: protos/v1/rocket.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rocket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Flights int32  `protobuf:"varint,4,opt,name=flights,proto3" json:"flights,omitempty"`
}

func (x *Rocket) Reset() {
	*x = Rocket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_rocket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rocket) ProtoMessage() {}

func (x *Rocket) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_rocket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rocket.ProtoReflect.Descriptor instead.
func (*Rocket) Descriptor() ([]byte, []int) {
	return file_protos_v1_rocket_proto_rawDescGZIP(), []int{0}
}

func (x *Rocket) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rocket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rocket) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Rocket) GetFlights() int32 {
	if x != nil {
		return x.Flights
	}
	return 0
}

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_rocket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_rocket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_protos_v1_rocket_proto_rawDescGZIP(), []int{1}
}

func (x *GetReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rocket *Rocket `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
}

func (x *GetRes) Reset() {
	*x = GetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_rocket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRes) ProtoMessage() {}

func (x *GetRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_rocket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRes.ProtoReflect.Descriptor instead.
func (*GetRes) Descriptor() ([]byte, []int) {
	return file_protos_v1_rocket_proto_rawDescGZIP(), []int{2}
}

func (x *GetRes) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

type SetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rocket *Rocket `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
}

func (x *SetReq) Reset() {
	*x = SetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_rocket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReq) ProtoMessage() {}

func (x *SetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_rocket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReq.ProtoReflect.Descriptor instead.
func (*SetReq) Descriptor() ([]byte, []int) {
	return file_protos_v1_rocket_proto_rawDescGZIP(), []int{3}
}

func (x *SetReq) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

type SetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rocket *Rocket `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
}

func (x *SetRes) Reset() {
	*x = SetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_rocket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRes) ProtoMessage() {}

func (x *SetRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_rocket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRes.ProtoReflect.Descriptor instead.
func (*SetRes) Descriptor() ([]byte, []int) {
	return file_protos_v1_rocket_proto_rawDescGZIP(), []int{4}
}

func (x *SetRes) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

type RemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemReq) Reset() {
	*x = RemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_rocket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemReq) ProtoMessage() {}

func (x *RemReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_rocket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemReq.ProtoReflect.Descriptor instead.
func (*RemReq) Descriptor() ([]byte, []int) {
	return file_protos_v1_rocket_proto_rawDescGZIP(), []int{5}
}

func (x *RemReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemRes) Reset() {
	*x = RemRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_rocket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemRes) ProtoMessage() {}

func (x *RemRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_rocket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemRes.ProtoReflect.Descriptor instead.
func (*RemRes) Descriptor() ([]byte, []int) {
	return file_protos_v1_rocket_proto_rawDescGZIP(), []int{6}
}

func (x *RemRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_protos_v1_rocket_proto protoreflect.FileDescriptor

var file_protos_v1_rocket_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x22, 0x5a, 0x0a, 0x06, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x18, 0x0a, 0x06,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x26, 0x0a, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x30, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x30, 0x0a, 0x06, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x18, 0x0a, 0x06,
	0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x96, 0x01, 0x0a, 0x0d, 0x52, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x52, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x52, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_v1_rocket_proto_rawDescOnce sync.Once
	file_protos_v1_rocket_proto_rawDescData = file_protos_v1_rocket_proto_rawDesc
)

func file_protos_v1_rocket_proto_rawDescGZIP() []byte {
	file_protos_v1_rocket_proto_rawDescOnce.Do(func() {
		file_protos_v1_rocket_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_v1_rocket_proto_rawDescData)
	})
	return file_protos_v1_rocket_proto_rawDescData
}

var file_protos_v1_rocket_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_v1_rocket_proto_goTypes = []interface{}{
	(*Rocket)(nil), // 0: rocket.Rocket
	(*GetReq)(nil), // 1: rocket.GetReq
	(*GetRes)(nil), // 2: rocket.GetRes
	(*SetReq)(nil), // 3: rocket.SetReq
	(*SetRes)(nil), // 4: rocket.SetRes
	(*RemReq)(nil), // 5: rocket.RemReq
	(*RemRes)(nil), // 6: rocket.RemRes
}
var file_protos_v1_rocket_proto_depIdxs = []int32{
	0, // 0: rocket.GetRes.rocket:type_name -> rocket.Rocket
	0, // 1: rocket.SetReq.rocket:type_name -> rocket.Rocket
	0, // 2: rocket.SetRes.rocket:type_name -> rocket.Rocket
	1, // 3: rocket.RocketService.GetRocket:input_type -> rocket.GetReq
	3, // 4: rocket.RocketService.SetRocket:input_type -> rocket.SetReq
	5, // 5: rocket.RocketService.RemRocket:input_type -> rocket.RemReq
	2, // 6: rocket.RocketService.GetRocket:output_type -> rocket.GetRes
	4, // 7: rocket.RocketService.SetRocket:output_type -> rocket.SetRes
	6, // 8: rocket.RocketService.RemRocket:output_type -> rocket.RemRes
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_v1_rocket_proto_init() }
func file_protos_v1_rocket_proto_init() {
	if File_protos_v1_rocket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_v1_rocket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rocket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_rocket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_rocket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_rocket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_rocket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_rocket_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_rocket_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_v1_rocket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_v1_rocket_proto_goTypes,
		DependencyIndexes: file_protos_v1_rocket_proto_depIdxs,
		MessageInfos:      file_protos_v1_rocket_proto_msgTypes,
	}.Build()
	File_protos_v1_rocket_proto = out.File
	file_protos_v1_rocket_proto_rawDesc = nil
	file_protos_v1_rocket_proto_goTypes = nil
	file_protos_v1_rocket_proto_depIdxs = nil
}
